### PR TITLE
Fixed Broken API, Added Search Bar

### PR DESCRIPTION
**Pull request by NiketanG**
:bug: Switched from old broken API to HTML Parsing using Fetch. Issue: [4](https://github.com/DeltaCoderr/live-follower-tracker/issues/4)
:sparkles: Added Search Bar to search for user using username. Issue: [1](https://github.com/DeltaCoderr/live-follower-tracker/issues/1)
:memo: Details like Name & Instagram Profile Link are shown.
:goal_net:  Proper error message is shown when User is not found.

### CODE REVIEW

**Comment by sbdh11** [comment]
ok this is epic, Thanks for doing this!

**Comment by NiketanG** [comment]
Could you please add 'hacktoberfest-accepted' label to the PR ? Only that way it'll count cause they've updated the rules. Thank you.

**Comment by sbdh11** [comment]
aight

**Comment by sbdh11** [comment]
Uhh but, the people who did this before 3rd of October. These PRS still count.

**Pull request merged**
